commandesPhysiques:
    path:     /liste
    defaults: { _controller: BenchmarkingBundle:CommandePhysique:index }

commandePhysique_view:
    path:     /{id}
    defaults: { _controller: BenchmarkingBundle:CommandePhysique:view }
    requirements:
        id: \d*

commandePhysique_add:
    path:     /add
    defaults: { _controller: BenchmarkingBundle:CommandePhysique:add }
    requirements:
        id: \d*

commandePhysique_edit:
    path:     /tedit/{id}
    defaults: { _controller: BenchmarkingBundle:CommandePhysique:edit }
    requirements:
        id: \d*

commandePhysique_delete:
    path:     /delete/{id}
    defaults: { _controller: BenchmarkingBundle:CommandePhysique:delete }
    requirements:
        id: \d*
