
vehicule_add:
    path:     /add
    defaults: { _controller: BenchmarkingBundle:Vehicule:add }

vehicule_edit:
    path:    /edit/{id}
    defaults: { _controller: BenchmarkingBundle:Vehicule:edit }
    requirements:
        id: \d*

vehicule_delete:
    path:     /delete/{id}
    defaults: { _controller: BenchmarkingBundle:Vehicule:delete }
    requirements:
        id: \d*
