admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

benchmarking:
    resource: "@BenchmarkingBundle/Resources/config/routing.yml"
    prefix:   /
